title: Net-Doc

theme: bulma-clean-theme
force_theme: light

baseurl: /net-doc
hide_share_buttons: true

defaults:
  - scope:
      path: 'docs'
    values:
      layout: page
      toc: true
      menubar: docs_menu
